# Generated by Django 2.2.3 on 2019-07-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ipv4', models.IntegerField(blank=True, default=0, null=True)),
                ('ipv6', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
