# Generated by Django 2.2.3 on 2019-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ipv',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ipv',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=12),
        ),
    ]
